from tkinter import *
import pygame
pygame.init()
pygame.mixer.music.load('Audio/music.mp3')
pygame.mixer.music.play()
janela = Tk()
janela.title('Quiz Of Tecnology 1.0')
janela.geometry('1200x630')
janela.configure(background='black')
font = ('Arial', '25', 'bold')

#   IMAGENS:

image1 = PhotoImage(file="Imagens/bg.gif")
image1 = image1.subsample(1, 1)
labelimage = Label(bg='black', image=image1)
labelimage.place(x=5, y=5, relwidth=1.0, relheight=1.0)

image2 = PhotoImage(file="Imagens/comojogar.gif")
image2 = image2.subsample(1, 1)
labelimage2 = Label(bg='black', image=image2)

image3 = PhotoImage(file="Imagens/bk2.gif")  # 1
image3 = image3.subsample(1, 1)
labelimage3 = Label(bg='black', image=image3)

image4 = PhotoImage(file="Imagens/bk3.gif")  # 2
image4 = image4.subsample(1, 1)
labelimage4 = Label(bg='black', image=image4)

image5 = PhotoImage(file="Imagens/bk4.gif")  # 3
image5 = image5.subsample(1, 1)
labelimage5 = Label(bg='black', image=image5)

image6 = PhotoImage(file="Imagens/bk5.gif")  # 4
image6 = image6.subsample(1, 1)
labelimage6 = Label(bg='black', image=image6)

image7 = PhotoImage(file="Imagens/bk6.gif")  # 5
image7 = image7.subsample(1, 1)
labelimage7 = Label(bg='black', image=image7)

image8 = PhotoImage(file="Imagens/bk7.gif")  # 6
image8 = image8.subsample(1, 1)
labelimage8 = Label(bg='black', image=image8)

image9 = PhotoImage(file="Imagens/bk8.gif")  # 7
image9 = image9.subsample(1, 1)
labelimage9 = Label(bg='black', image=image9)

image10 = PhotoImage(file="Imagens/bk9.gif")  # 8
image10 = image10.subsample(1, 1)
labelimage10 = Label(bg='black', image=image10)

image11 = PhotoImage(file="Imagens/bk10.gif")  # 9
image11 = image11.subsample(1, 1)
labelimage11 = Label(bg='black', image=image11)

image12 = PhotoImage(file="Imagens/bk.gif")  # 10
image12 = image12.subsample(1, 1)
labelimage12 = Label(bg='black', image=image12)

image13 = PhotoImage(file="Imagens/bk11.gif")  # 11
image13 = image13.subsample(1, 1)
labelimage13 = Label(bg='black', image=image13)

imageover = PhotoImage(file="Imagens/gameover.gif")  # 11
imageover = imageover.subsample(1, 1)
labelimageover = Label(bg='black', image=imageover)

imageganhou = PhotoImage(file="Imagens/ganhou.gif")  # 11
imageganhou = imageganhou.subsample(1, 1)
labelimageganhou = Label(bg='black', image=imageganhou)


#   FRAMES:

frame1 = Frame(janela)  # Botões de iniciar jogo e como jogar.
frame2 = Frame(janela)  # Botões das disciplinas
framep = Frame(janela)  # Label de perguntas.
frameb = Frame(janela)  # botões das alternativas.
framer = Frame(janela)  # reiniciar
framej = Frame(janela)
frame1.pack(side=BOTTOM, pady='200')  # Botões empacotados de "iniciar" e "como jogar".
framep.pack(pady='90')
frameb.pack(side=BOTTOM, pady='100', padx='1')


#   FUNÇÕES:


def pergunta0():
    labelimage3.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    pergunta00.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A.pack()
    B.pack()
    C.pack()
    D.pack()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimage.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    framer.pack_forget()
    frame1.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta1():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage4.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta01.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A1.pack()
    B1.pack()
    C1.pack()
    D1.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta00.pack_forget()
    A.pack_forget()
    B.pack_forget()
    C.pack_forget()
    D.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta2():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage5.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta02.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A2.pack()
    B2.pack()
    C2.pack()
    D2.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta01.pack_forget()
    A1.pack_forget()
    B1.pack_forget()
    C1.pack_forget()
    D1.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta3():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage6.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta03.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A3.pack()
    B3.pack()
    C3.pack()
    D3.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta02.pack_forget()
    A2.pack_forget()
    B2.pack_forget()
    C2.pack_forget()
    D2.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta4():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage7.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimageover.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    pergunta04.pack()
    A4.pack()
    B4.pack()
    C4.pack()
    D4.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta03.pack_forget()
    A3.pack_forget()
    B3.pack_forget()
    C3.pack_forget()
    D3.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta5():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage8.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta05.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A5.pack()
    B5.pack()
    C5.pack()
    D5.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta04.pack_forget()
    A4.pack_forget()
    B4.pack_forget()
    C4.pack_forget()
    D4.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta6():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage9.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta06.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A6.pack()
    B6.pack()
    C6.pack()
    D6.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta05.pack_forget()
    A5.pack_forget()
    B5.pack_forget()
    C5.pack_forget()
    D5.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta7():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage10.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta07.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A7.pack()
    B7.pack()
    C7.pack()
    D7.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta06.pack_forget()
    A6.pack_forget()
    B6.pack_forget()
    C6.pack_forget()
    D6.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta8():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage11.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta08.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A8.pack()
    B8.pack()
    C8.pack()
    D8.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta07.pack_forget()
    A7.pack_forget()
    B7.pack_forget()
    C7.pack_forget()
    D7.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta9():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage12.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta09.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A9.pack()
    B9.pack()
    C9.pack()
    D9.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta08.pack_forget()
    A8.pack_forget()
    B8.pack_forget()
    C8.pack_forget()
    D8.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()
    

def pergunta10():
    pygame.mixer.music.load('Audio/acertou.mp3')
    pygame.mixer.music.play()
    labelimage13.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimageganhou.place_forget()
    reiniciar.pack_forget()
    pergunta010.pack()
    framep.pack(pady='90')
    frameb.pack(side=BOTTOM, pady='130', padx='1')
    A10.pack()
    B10.pack()
    C10.pack()
    D10.pack()
    framer.pack_forget()
    frame1.pack_forget()
    pergunta09.pack_forget()
    A9.pack_forget()
    B9.pack_forget()
    C9.pack_forget()
    D9.pack_forget()
    iniciarjogo.pack_forget()
    comojogar.pack_forget()


def gameover():
    pygame.mixer.music.load('Audio/errou.mp3')
    pygame.mixer.music.play()
    labelimageover.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    reiniciar.pack()
    framer.pack(side=BOTTOM, pady='250', padx='1')
    reiniciar2.pack_forget()
    framep.pack_forget()
    frameb.pack_forget()
    labelimage.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageganhou.place_forget()
    pergunta00.pack_forget()
    pergunta01.pack_forget()
    pergunta02.pack_forget()
    pergunta03.pack_forget()
    pergunta04.pack_forget()
    pergunta05.pack_forget()
    pergunta06.pack_forget()
    pergunta07.pack_forget()
    pergunta08.pack_forget()
    pergunta09.pack_forget()
    pergunta010.pack_forget()
    A.pack_forget()
    B.pack_forget()
    C.pack_forget()
    D.pack_forget()
    A1.pack_forget()
    B1.pack_forget()
    C1.pack_forget()
    D1.pack_forget()
    A2.pack_forget()
    B2.pack_forget()
    C2.pack_forget()
    D2.pack_forget()
    A3.pack_forget()
    B3.pack_forget()
    C3.pack_forget()
    D3.pack_forget()
    A4.pack_forget()
    B4.pack_forget()
    C4.pack_forget()
    D4.pack_forget()
    A5.pack_forget()
    B5.pack_forget()
    C5.pack_forget()
    D5.pack_forget()
    A6.pack_forget()
    B6.pack_forget()
    C6.pack_forget()
    D6.pack_forget()
    A7.pack_forget()
    B7.pack_forget()
    C7.pack_forget()
    D7.pack_forget()
    A8.pack_forget()
    B8.pack_forget()
    C8.pack_forget()
    D8.pack_forget()
    A9.pack_forget()
    B9.pack_forget()
    C9.pack_forget()
    D9.pack_forget()
    A10.pack_forget()
    B10.pack_forget()
    C10.pack_forget()
    D10.pack_forget()
    

def certo():
    pygame.mixer.music.load('Audio/aplausos.mp3')
    pygame.mixer.music.play()
    labelimageganhou.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    reiniciar2.pack()
    framer.pack(side=BOTTOM, pady='250', padx='1')
    labelimage.place_forget()
    labelimage2.place_forget()
    labelimage3.place_forget()
    labelimage4.place_forget()
    labelimage5.place_forget()
    labelimage6.place_forget()
    labelimage7.place_forget()
    labelimage8.place_forget()
    labelimage9.place_forget()
    labelimage10.place_forget()
    labelimage11.place_forget()
    labelimage12.place_forget()
    labelimage13.place_forget()
    labelimageover.place_forget()
    pergunta010.pack_forget()
    pergunta010.pack_forget()
    A10.pack_forget()
    B10.pack_forget()
    C10.pack_forget()
    D10.pack_forget()
    frameb.pack_forget()
    framep.pack_forget()
    

def comojogar0():
    iniciarjogo.pack()
    comojogar.pack_forget()
    labelimage2.place(x=5, y=5, relwidth=1.0, relheight=1.0)
    frameb.pack_forget()
    music()


def music():
    pygame.mixer.music.load('Audio/music.mp3')
    pygame.mixer.music.play()


#   WIDJETS:

iniciarjogo = Button(frame1, text='Iniciar Jogo', font='80', width='35', bg='black', fg='white', command=pergunta0)
iniciarjogo.pack(side=LEFT)
comojogar = Button(frame1, text='Como Jogar', font='80', width='35', bg='black', fg='white', command=comojogar0)
comojogar.pack(side=RIGHT)
reiniciar = Button(framer, text='Tentar Novamente', font='80', width='0', bg='green', fg='white', command=pergunta0)
reiniciar2 = Button(framer, text='Jogar novamente', font='80', width='0', bg='green', fg='white', command=pergunta0)

pergunta00 = Label(framep, text='Responda: ?', font=font, bg='white', fg='black')
A = Button(frameb, text='PDP-1', font='80', width='35', bg='black', fg='white', command=gameover)
B = Button(frameb, text='EDVAC', font='80', width='35', bg='black', fg='white', command=gameover)
C = Button(frameb, text='COLOSSUS', font='80', width='35', bg='black', fg='white', command=gameover)
D = Button(frameb, text='ENIAC', font='80', width='35', bg='black', fg='white', command=pergunta1)

pergunta01 = Label(framep, text='Responda: O que é a internet?', font=font, bg='white', fg='black')
A1 = Button(frameb, text='É uma rede de computadores \n interconectados a milhões de dispositivos.', font='80',
            width='35', bg='black', fg='white', command=pergunta2)
B1 = Button(frameb, text='É o Google Chrome', font='80', width='35', bg='black', fg='white', command=gameover)
C1 = Button(frameb, text='É um Roteador Wi-Fi', font='80', width='35', bg='black', fg='white', command=gameover)
D1 = Button(frameb, text='É um centro de reabilitação', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta02 = Label(framep, text='Responda: O que é um software?', font=font, bg='white', fg='black')
A2 = Button(frameb, text='um vírus', font='80', width='35', bg='black', fg='white', command=gameover)
B2 = Button(frameb, text='uma partição', font='80', width='35', bg='black', fg='white', command=gameover)
C2 = Button(frameb, text='parte física do computador', font='80', width='35', bg='black', fg='white', command=gameover)
D2 = Button(frameb, text='parte lógica do computador', font='80', width='35', bg='black', fg='white', command=pergunta3)

pergunta03 = Label(framep, text='Responda: O que é peopleware?', font=font, bg='white', fg='black')
A3 = Button(frameb, text='Usuários do computador', font='80', width='35', bg='black', fg='white', command=pergunta4)
B3 = Button(frameb, text='Um cavalo de tróia', font='80', width='35', bg='black', fg='white', command=gameover)
C3 = Button(frameb, text='Numeração de dados', font='80', width='35', bg='black', fg='white', command=gameover)
D3 = Button(frameb, text='Software que gera outro software', font='80', width='35', bg='black', fg='white',
            command=gameover)

pergunta04 = Label(framep, text='Responda: Qual das 4 opções não é uma topologia?', font=font, bg='white', fg='black')
A4 = Button(frameb, text='Anel', font='80', width='35', bg='black', fg='white', command=gameover)
B4 = Button(frameb, text='Estrela', font='80', width='35', bg='black', fg='white', command=gameover)
C4 = Button(frameb, text='Barragem', font='80', width='35', bg='black', fg='white', command=pergunta5)
D4 = Button(frameb, text='Barramento', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta05 = Label(framep, text='Responda: Em que ano a Internet foi originada?', font=font, bg='white', fg='black')
A5 = Button(frameb, text='1960', font='80', width='35', bg='black', fg='white', command=gameover)
B5 = Button(frameb, text='1970', font='80', width='35', bg='black', fg='white', command=gameover)
C5 = Button(frameb, text='1980', font='80', width='35', bg='black', fg='white', command=pergunta6)
D5 = Button(frameb, text='1990', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta06 = Label(framep, text='Responda: Qual o significado da sígla "PAN"?', font=font, bg='white', fg='black')
A6 = Button(frameb, text='P-Link Add Net', font='80', width='35', bg='black', fg='white', command=gameover)
B6 = Button(frameb, text='Python American National', font='80', width='35', bg='black', fg='white', command=gameover)
C6 = Button(frameb, text='Person Adblock Number', font='80', width='35', bg='black', fg='white', command=gameover)
D6 = Button(frameb, text='Personal Area Network', font='80', width='35', bg='black', fg='white', command=pergunta7)

pergunta07 = Label(framep, text='Responda: Qual o significado da sígla "WWW"?', font=font, bg='white', fg='black')
A7 = Button(frameb, text='World Wise Web', font='80', width='35', bg='black', fg='white', command=gameover)
B7 = Button(frameb, text='Word Wide Web', font='80', width='35', bg='black', fg='white', command=gameover)
C7 = Button(frameb, text='World Wide Web', font='80', width='35', bg='black', fg='white', command=pergunta8)
D7 = Button(frameb, text='Wid Word Web', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta08 = Label(framep, text='A rede MAN abrange...?', font=font, bg='white', fg='black')
A8 = Button(frameb, text='Uma cidade', font='80', width='35', bg='black', fg='white', command=pergunta9)
B8 = Button(frameb, text='Um país', font='80', width='35', bg='black', fg='white', command=gameover)
C8 = Button(frameb, text='Um continente', font='80', width='35', bg='black', fg='white', command=gameover)
D8 = Button(frameb, text='Não tem limítes', font='80', width='35', bg='black', fg='white', command=gameover)

pergunta09 = Label(framep, text='Responda: Qual dos fatores abaixo marcou a primeira era dos computadores?', font=font,
                   bg='white', fg='black')
A9 = Button(frameb, text='Uso de válvulas', font='80', width='35', bg='black', fg='white', command=pergunta10)
B9 = Button(frameb, text='Uso de transistores', font='80', width='35', bg='black', fg='white', command=gameover)
C9 = Button(frameb, text='Uso de chips', font='80', width='35', bg='black', fg='white', command=gameover)
D9 = Button(frameb, text='Uso de computadores pessoais', font='80', width='35', bg='black', fg='white',
            command=gameover)

pergunta010 = Label(framep, text='Responda: Qual é a proposição que é representada por "se p então q"?', font=font,
                    bg='white', fg='black')
A10 = Button(frameb, text='Condicional', font='80', width='35', bg='black', fg='white', command=certo)
B10 = Button(frameb, text='Disjunção', font='80', width='35', bg='black', fg='white', command=gameover)
C10 = Button(frameb, text='Bicondicional', font='80', width='35', bg='black', fg='white', command=gameover)
D10 = Button(frameb, text='Conjunção', font='80', width='35', bg='black', fg='white', command=gameover)

janela.mainloop()
